server:
  port: 8080

spring:
  application:
    name: spring-boot-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/sample
    username: postgres
    password: 1234
  h2:
    console:
      enabled: false

  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: false
    url: jdbc:postgresql://localhost:5432/sample
    user: postgres
    password: 1234

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace